server:
  port: 10080

spring:
  application:
    name: order-service-${server.port}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-7001:7001/eureka/, http://eureka-server-7002:7002/eureka/
