server:
  port: 8001

spring:
  application:
    name: payment-service-${server.port}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 10
