spring:
  application:
    name: gateway-service
server:
  port: 11220
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-7001:7001/eureka/, http://eureka-server-7002:7002/eureka/