server:
  port: 8111

spring:
  application:
    name: payment-service-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-7001:7001/eureka/, http://eureka-server-7002:7002/eureka/
