server:
  port: 8002

spring:
  application:
    name: payment-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-7001:7001/eureka/, http://eureka-server-7002:7002/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 10
